name: Publish Release
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Get current code from GitHub
      - name: Checkout
        uses: actions/checkout@v4
      # Install Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 23
      # Read version number from gradle.properties
      - name: Read project version
        id: read-version
        uses: BrycensRanch/read-properties-action@v1
        with:
          file: gradle.properties
          property: project_version
      # Set up caching of gradle dependencies for speed
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      # Make gradle wrapper executable for linux
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      # Build project (runs tests and ensure that regular build works)
      - name: Build with Gradle
        run: ./gradlew build
      # Upload image to the container repository (:latest tag)
      - name: Build and upload image
        run: ./gradlew jib -Djib.to.image=ghcr.io/suvisyrjalainen/stars-toolbox:latest
        env:
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Upload image to the container repository (version tag)
      - name: Build and upload image
        run: ./gradlew jib -Djib.to.image=ghcr.io/suvisyrjalainen/stars-toolbox:${{ steps.read-version.outputs.project_version }}
        env:
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Create GitHub release for version tagging
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.read-version.outputs.project_version }}
          name: Version ${{ steps.read-version.outputs.project_version }}
          generate_release_notes: true
          make_latest: true
          files:
            build/libs/*.jar